#!/bin/bash

# Author: Bruno Novaes
# Date Created: 13/03/2025
# Last Modified: 13/03/2025

# Description
# Basic calculator

# Usage
# basic_calculator

# echo $(( ${2:-0} $1 ${3:-0} $1 ${4:-0} $1 ${5:-0} $1 ${6:-0} $1 ${7:-0} $1 ${8:-0} $1 ${9:-0} $1 ${10:-0} ))

echo $(( $@ ))
